### PR TITLE
Added English localization file

### PR DESCRIPTION
**Pull request by mimmiechan**
I used Google Translate to translate the strings into English, since I do not know any Chinese nor Japanese (the two languages currently supported). I manually reviewed each line to make everything consistent and understandable. I used both the Chinese and the Japanese localizations for reference. A few things I did not know how to make perfect sense of, and it isn't perfect, but still, the program is highly usable as an English speaker if this localization file is added.

### CODE REVIEW

**Comment by mimmiechan** [comment]
I spent the whole day trying to find a good FOSS context menu editor (could not find any other that matched my needs), figuring out how to compile C# .NET 3.5 software and "translating" the program. I hope you consider accepting this pull request. I am sure that it will help some people who do not speak Chinese or Japanese.

**Comment by BluePointLilac** [comment]
Thank you, good job!

**Comment by BluePointLilac** [comment]
I use Visual Studio 2019 write this program, double click properites can change .net version, just only run with .net 3.5 or 4.0+

**Comment by mimmiechan** [comment]
> 
> 
> Thank you, good job!

Thanks, I'm happy you merged it!



> 
> 
> I use Visual Studio 2019 write this program, double click properites can change .net version, just only run with .net 3.5 or 4.0+

Thanks. I did not want to install VS, that would have been too easy! I ended up installing only the VS Build Tools 2019 using the Visual Studio Installer (via Chocolatey actually.) Then it was as simple as opening its "Developer Command Prompt", navigating to the source code (or maybe use git or whatever) and run `msbuild ContextMenuManager.sln`.

**Pull request merged**
