### PR TITLE
Create ar-DZ.ini

### PR DESCRIPTION
**Pull request by bouzidzerougdz**
I would like to inform you that I have successfully translated the program into Arabic. I just wanted to thank the developer for their great efforts in developing this useful program, and for making a wonderful effort to provide it and make it available to everyone.

Thank you again for your efforts, and I look forward to enjoying using this program smoothly in Arabic.

Best regards,
[Bouzid Zeroug]

### CODE REVIEW

**Comment by BluePointLilac** [comment]
Thank you very much for your translation, I am planning to write a new version of the management tool, and you may need to pay attention to the need to re-translate.

**Comment by bouzidzerougdz** [comment]
This is my pleasure.

في الأحد، 5 مايو 2024، 09:04 蓝点lilac ***@***.***> كتب:

**Comment by bouzidzerougdz** [comment]
Sorry for the inconvenience, but there is a mistake. The name of the
translation file should be " ar-DZ.ini "; note that the file is in " ini "
format.

‫في الأحد، 5 مايو 2024 في 4:12 م تمت كتابة ما يلي بواسطة ‪BOUZID ZEROUG‬‏ <‪
***@***.***‬‏>:‬

**Comment by gaoqiangks** [comment]
> Thank you very much for your translation, I am planning to write a new version of the management tool, and you may need to pay attention to the need to re-translate.

新的版本怎么样了，大佬， 一直等着呢

**Pull request merged**
